export const properties = [
  {
    id: 1,
    title: "Modern 2 Bedroom Apartment In New York.",
    location: "Downtown, New York",
    price: "$1,200",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    type: "Apartments",
    features: "2 Baths • 2 Beds • 1200 sqft",
    rating: 4.5,
    liked: true,
    description: "A beautiful and spacious apartment located in the heart of downtown New York. This modern apartment offers an open floor plan, updated kitchen, and stunning city views. Perfect for professionals and families alike, it features hardwood floors, high ceilings, and abundant natural light.",
    reviews: "4.5 out of 5 stars",
  },
  {
    id: 2,
    title: "Luxury Beachfront Villa in Goa",
    location: "South Goa, India",
    price: "$1,80,000",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
    type: "Villa",
    features: "4 Baths • 4 Beds • 3000 sqft",
    rating: 4.8,
    liked: false,
    description: "A beautiful and spacious apartment located in the heart of downtown New York. This modern apartment offers an open floor plan, updated kitchen, and stunning city views. Perfect for professionals and families alike, it features hardwood floors, high ceilings, and abundant natural light.",
    reviews: "4.5 out of 5 stars",
  },
  {
    id: 3,
    title: "Affordable City Apartment",
    location: "Mumbai Central",
    price: "$45,000",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
    type: "Apartments",
    features: "1 Bath • 1 Bed • 600 sqft",
    rating: 4.1,
    liked: false,
    description: "A beautiful and spacious apartment located in the heart of downtown New York. This modern apartment offers an open floor plan, updated kitchen, and stunning city views. Perfect for professionals and families alike, it features hardwood floors, high ceilings, and abundant natural light.",
    reviews: "4.5 out of 5 stars",
  },
  {
    id: 4,
    title: "Cozy Family House",
    location: "Bangalore Suburb",
    price: "$75,000",
    image: "https://images.unsplash.com/photo-1599423300746-b62533397364",
    type: "House",
    features: "2 Baths • 3 Beds • 1500 sqft",
    rating: 4.3,
    liked: true,
    description: "A beautiful and spacious apartment located in the heart of downtown New York. This modern apartment offers an open floor plan, updated kitchen, and stunning city views. Perfect for professionals and families alike, it features hardwood floors, high ceilings, and abundant natural light.",
    reviews: "4.5 out of 5 stars",
  },
];
